version: '2'
services:
    emkc:
        container_name: emkc
        build: .
        ports:
            - "2727:2727"
        volumes:
            - ./:/opt/emkc
        links:
            - redis
            - mysql
        extra_hosts:
            vortex: 172.17.0.1
    redis:
        image: redis:3.2.12
        volumes:
            - ./:/opt/emkc
            - ./var/docker/redis:/data
    mysql:
        image: mysql:5.6
        ports:
            - "33061:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: emkc
        command: --init-file /var/lib/init/db.sql
        volumes:
            - ./:/opt/emkc
            - ./var/docker/mysql:/var/lib/mysql
            - ./var/docker/init:/var/lib/init
            - ./var/docker/config:/etc/mysql/conf.d
